In [2]:
#ggplot
#dyplr para manipulacion de datos(Algo como lo que harias con pandas)

In [4]:
#Operador pipe &>%
install.packages("gapminder")
library(gapminder)
data(gapminder)

package 'gapminder' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\itzam\AppData\Local\Temp\RtmpuE3iZw\downloaded_packages

Warning message:
"package 'gapminder' was built under R version 3.6.3"

In [5]:
head(gapminder,2)

  country     continent year lifeExp pop     gdpPercap
1 Afghanistan Asia      1952 28.801  8425333 779.4453
2 Afghanistan Asia      1957 30.332  9240934 820.8530

In [6]:
install.packages('tidyverse')
library(tidyverse)

also installing the dependencies 'bit', 'bit64', 'progress', 'blob', 'glue', 'tidyselect', 'data.table', 'cli', 'gargle', 'ids', 'cpp11', 'vroom', 'tzdb', 'broom', 'dbplyr', 'dplyr', 'dtplyr', 'forcats', 'googledrive', 'googlesheets4', 'haven', 'hms', 'jsonlite', 'lubridate', 'modelr', 'readr', 'reprex', 'rvest', 'tidyr'

  There are binary versions available but the source versions are later:
              binary source needs_compilation
blob           1.2.1  1.2.2             FALSE
cli            2.5.0  3.0.1              TRUE
gargle         1.1.0  1.2.0             FALSE
cpp11          0.2.7  0.3.1             FALSE
vroom          1.4.0  1.5.4              TRUE
tzdb           0.1.1  0.1.2              TRUE
broom          0.7.6  0.7.9             FALSE
dplyr          1.0.6  1.0.7              TRUE
googledrive    1.0.1  2.0.0             FALSE
googlesheets4  0.3.0  1.0.0             FALSE
haven          2.4.1  2.4.3              TRUE
hms            1.0.0  1.1.0             FALSE
readr          1.4.0  2.0.0              TRUE
reprex         2.0.0  2.0.1             FALSE
rvest          1.0.0  1.0.1             FALSE

  Binaries will be installed
package 'bit' successfully unpacked and MD5 sums checked
package 'bit64' successfully unpacked and MD5 sums checked
package 'progress' successfully unpacked and MD5 sums checked
package 'glue' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'glue'"Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problema al copiar C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\00LOCK\glue\libs\x64\glue.dll  a C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\glue\libs\x64\glue.dll: Permission denied"Warning message:
"restored 'glue'"

package 'tidyselect' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'tidyselect'"Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problema al copiar C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\00LOCK\tidyselect\libs\x64\tidyselect.dll  a C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\tidyselect\libs\x64\tidyselect.dll: Permission denied"Warning message:
"restored 'tidyselect'"

package 'data.table' successfully unpacked and MD5 sums checked
package 'cli' successfully unpacked and MD5 sums checked
package 'ids' successfully unpacked and MD5 sums checked
package 'vroom' successfully unpacked and MD5 sums checked
package 'tzdb' successfully unpacked and MD5 sums checked
package 'dbplyr' successfully unpacked and MD5 sums checked
package 'dplyr' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'dplyr'"Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problema al copiar C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\00LOCK\dplyr\libs\x64\dplyr.dll  a C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\dplyr\libs\x64\dplyr.dll: Permission denied"Warning message:
"restored 'dplyr'"

package 'dtplyr' successfully unpacked and MD5 sums checked
package 'forcats' successfully unpacked and MD5 sums checked
package 'haven' successfully unpacked and MD5 sums checked
package 'jsonlite' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'jsonlite'"Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problema al copiar C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\00LOCK\jsonlite\libs\x64\jsonlite.dll  a C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\jsonlite\libs\x64\jsonlite.dll: Permission denied"Warning message:
"restored 'jsonlite'"

package 'lubridate' successfully unpacked and MD5 sums checked
package 'modelr' successfully unpacked and MD5 sums checked
package 'readr' successfully unpacked and MD5 sums checked

Warning message:
"cannot remove prior installation of package 'readr'"Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problema al copiar C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\00LOCK\readr\libs\x64\librcon.lib  a C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\readr\libs\x64\librcon.lib: Permission denied"Warning message in file.copy(savedcopy, lib, recursive = TRUE):
"problema al copiar C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\00LOCK\readr\libs\x64\readr.dll  a C:\Users\itzam\anaconda3\envs\Renviroment\Lib\R\library\readr\libs\x64\readr.dll: Permission denied"Warning message:
"restored 'readr'"

package 'tidyr' successfully unpacked and MD5 sums checked
package 'tidyverse' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\itzam\AppData\Local\Temp\RtmpuE3iZw\downloaded_packages

installing the source packages 'blob', 'gargle', 'cpp11', 'broom', 'googledrive', 'googlesheets4', 'hms', 'reprex', 'rvest'

Warning message in install.packages("tidyverse"):
"installation of package 'broom' had non-zero exit status"Warning message in install.packages("tidyverse"):
"installation of package 'googledrive' had non-zero exit status"Warning message in install.packages("tidyverse"):
"installation of package 'googlesheets4' had non-zero exit status"Warning message:
"package 'tidyverse' was built under R version 3.6.3"

ERROR: Error: package or namespace load failed for 'tidyverse' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'broom' 0.5.2 is being loaded, but >= 0.7.6 is required

In [11]:
#Filtramos sin usar operador pipe
gapminder[gapminder['country']=='Mexico',]

   country continent year lifeExp pop       gdpPercap
1  Mexico  Americas  1952 50.789   30144317  3478.126
2  Mexico  Americas  1957 55.190   35015548  4131.547
3  Mexico  Americas  1962 58.299   41121485  4581.609
4  Mexico  Americas  1967 60.110   47995559  5754.734
5  Mexico  Americas  1972 62.361   55984294  6809.407
6  Mexico  Americas  1977 65.032   63759976  7674.929
7  Mexico  Americas  1982 67.405   71640904  9611.148
8  Mexico  Americas  1987 69.498   80122492  8688.156
9  Mexico  Americas  1992 71.455   88111030  9472.384
10 Mexico  Americas  1997 73.670   95895146  9767.298
11 Mexico  Americas  2002 74.902  102479927 10742.441
12 Mexico  Americas  2007 76.195  108700891 11977.575

In [14]:
library(tidyverse)

Warning message:
"package 'tidyverse' was built under R version 3.6.3"

ERROR: Error: package or namespace load failed for 'tidyverse' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace 'broom' 0.5.2 is being loaded, but >= 0.7.6 is required

In [20]:
gapminder[gapminder['continent']=='Asia' ,]

    country            continent year lifeExp pop      gdpPercap
1   Afghanistan        Asia      1952 28.801   8425333   779.4453
2   Afghanistan        Asia      1957 30.332   9240934   820.8530
3   Afghanistan        Asia      1962 31.997  10267083   853.1007
4   Afghanistan        Asia      1967 34.020  11537966   836.1971
5   Afghanistan        Asia      1972 36.088  13079460   739.9811
6   Afghanistan        Asia      1977 38.438  14880372   786.1134
7   Afghanistan        Asia      1982 39.854  12881816   978.0114
8   Afghanistan        Asia      1987 40.822  13867957   852.3959
9   Afghanistan        Asia      1992 41.674  16317921   649.3414
10  Afghanistan        Asia      1997 41.763  22227415   635.3414
11  Afghanistan        Asia      2002 42.129  25268405   726.7341
12  Afghanistan        Asia      2007 43.828  31889923   974.5803
13  Bahrain            Asia      1952 50.939    120447  9867.0848
14  Bahrain            Asia      1957 53.832    138655 11635.7995
15  Bahrain            Asia      1962 56.923    171863 12753.2751
16  Bahrain            Asia      1967 59.923    202182 14804.6727
17  Bahrain            Asia      1972 63.300    230800 18268.6584
18  Bahrain            Asia      1977 65.593    297410 19340.1020
19  Bahrain            Asia      1982 69.052    377967 19211.1473
20  Bahrain            Asia      1987 70.750    454612 18524.0241
21  Bahrain            Asia      1992 72.601    529491 19035.5792
22  Bahrain            Asia      1997 73.925    598561 20292.0168
23  Bahrain            Asia      2002 74.795    656397 23403.5593
24  Bahrain            Asia      2007 75.635    708573 29796.0483
25  Bangladesh         Asia      1952 37.484  46886859   684.2442
26  Bangladesh         Asia      1957 39.348  51365468   661.6375
27  Bangladesh         Asia      1962 41.216  56839289   686.3416
28  Bangladesh         Asia      1967 43.453  62821884   721.1861
29  Bangladesh         Asia      1972 45.252  70759295   630.2336
30  Bangladesh         Asia      1977 46.923  80428306   659.8772
... ...                ...       ...  ...     ...      ...
367 Vietnam            Asia      1982 58.816  56142181  707.2358
368 Vietnam            Asia      1987 62.820  62826491  820.7994
369 Vietnam            Asia      1992 67.662  69940728  989.0231
370 Vietnam            Asia      1997 70.672  76048996 1385.8968
371 Vietnam            Asia      2002 73.017  80908147 1764.4567
372 Vietnam            Asia      2007 74.249  85262356 2441.5764
373 West Bank and Gaza Asia      1952 43.160   1030585 1515.5923
374 West Bank and Gaza Asia      1957 45.671   1070439 1827.0677
375 West Bank and Gaza Asia      1962 48.127   1133134 2198.9563
376 West Bank and Gaza Asia      1967 51.631   1142636 2649.7150
377 West Bank and Gaza Asia      1972 56.532   1089572 3133.4093
378 West Bank and Gaza Asia      1977 60.765   1261091 3682.8315
379 West Bank and Gaza Asia      1982 64.406   1425876 4336.0321
380 West Bank and Gaza Asia      1987 67.046   1691210 5107.1974
381 West Bank and Gaza Asia      1992 69.718   2104779 6017.6548
382 West Bank and Gaza Asia      1997 71.096   2826046 7110.6676
383 West Bank and Gaza Asia      2002 72.370   3389578 4515.4876
384 West Bank and Gaza Asia      2007 73.422   4018332 3025.3498
385 Yemen, Rep.        Asia      1952 32.548   4963829  781.7176
386 Yemen, Rep.        Asia      1957 33.970   5498090  804.8305
387 Yemen, Rep.        Asia      1962 35.180   6120081  825.6232
388 Yemen, Rep.        Asia      1967 36.984   6740785  862.4421
389 Yemen, Rep.        Asia      1972 39.848   7407075 1265.0470
390 Yemen, Rep.        Asia      1977 44.175   8403990 1829.7652
391 Yemen, Rep.        Asia      1982 49.113   9657618 1977.5570
392 Yemen, Rep.        Asia      1987 52.922  11219340 1971.7415
393 Yemen, Rep.        Asia      1992 55.599  13367997 1879.4967
394 Yemen, Rep.        Asia      1997 58.020  15826497 2117.4845
395 Yemen, Rep.        Asia      2002 60.308  18701257 2234.8208
396 Yemen, Rep.        Asia      2007 62.698  22211743 2280.7699

In [22]:
library(dplyr)

Attaching package: 'dplyr'

The following objects are masked from 'package:stats':

    filter, lag

The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

1

In [24]:
filter(gapminder,continent=='Asia')

    country            continent year lifeExp pop      gdpPercap
1   Afghanistan        Asia      1952 28.801   8425333   779.4453
2   Afghanistan        Asia      1957 30.332   9240934   820.8530
3   Afghanistan        Asia      1962 31.997  10267083   853.1007
4   Afghanistan        Asia      1967 34.020  11537966   836.1971
5   Afghanistan        Asia      1972 36.088  13079460   739.9811
6   Afghanistan        Asia      1977 38.438  14880372   786.1134
7   Afghanistan        Asia      1982 39.854  12881816   978.0114
8   Afghanistan        Asia      1987 40.822  13867957   852.3959
9   Afghanistan        Asia      1992 41.674  16317921   649.3414
10  Afghanistan        Asia      1997 41.763  22227415   635.3414
11  Afghanistan        Asia      2002 42.129  25268405   726.7341
12  Afghanistan        Asia      2007 43.828  31889923   974.5803
13  Bahrain            Asia      1952 50.939    120447  9867.0848
14  Bahrain            Asia      1957 53.832    138655 11635.7995
15  Bahrain            Asia      1962 56.923    171863 12753.2751
16  Bahrain            Asia      1967 59.923    202182 14804.6727
17  Bahrain            Asia      1972 63.300    230800 18268.6584
18  Bahrain            Asia      1977 65.593    297410 19340.1020
19  Bahrain            Asia      1982 69.052    377967 19211.1473
20  Bahrain            Asia      1987 70.750    454612 18524.0241
21  Bahrain            Asia      1992 72.601    529491 19035.5792
22  Bahrain            Asia      1997 73.925    598561 20292.0168
23  Bahrain            Asia      2002 74.795    656397 23403.5593
24  Bahrain            Asia      2007 75.635    708573 29796.0483
25  Bangladesh         Asia      1952 37.484  46886859   684.2442
26  Bangladesh         Asia      1957 39.348  51365468   661.6375
27  Bangladesh         Asia      1962 41.216  56839289   686.3416
28  Bangladesh         Asia      1967 43.453  62821884   721.1861
29  Bangladesh         Asia      1972 45.252  70759295   630.2336
30  Bangladesh         Asia      1977 46.923  80428306   659.8772
... ...                ...       ...  ...     ...      ...
367 Vietnam            Asia      1982 58.816  56142181  707.2358
368 Vietnam            Asia      1987 62.820  62826491  820.7994
369 Vietnam            Asia      1992 67.662  69940728  989.0231
370 Vietnam            Asia      1997 70.672  76048996 1385.8968
371 Vietnam            Asia      2002 73.017  80908147 1764.4567
372 Vietnam            Asia      2007 74.249  85262356 2441.5764
373 West Bank and Gaza Asia      1952 43.160   1030585 1515.5923
374 West Bank and Gaza Asia      1957 45.671   1070439 1827.0677
375 West Bank and Gaza Asia      1962 48.127   1133134 2198.9563
376 West Bank and Gaza Asia      1967 51.631   1142636 2649.7150
377 West Bank and Gaza Asia      1972 56.532   1089572 3133.4093
378 West Bank and Gaza Asia      1977 60.765   1261091 3682.8315
379 West Bank and Gaza Asia      1982 64.406   1425876 4336.0321
380 West Bank and Gaza Asia      1987 67.046   1691210 5107.1974
381 West Bank and Gaza Asia      1992 69.718   2104779 6017.6548
382 West Bank and Gaza Asia      1997 71.096   2826046 7110.6676
383 West Bank and Gaza Asia      2002 72.370   3389578 4515.4876
384 West Bank and Gaza Asia      2007 73.422   4018332 3025.3498
385 Yemen, Rep.        Asia      1952 32.548   4963829  781.7176
386 Yemen, Rep.        Asia      1957 33.970   5498090  804.8305
387 Yemen, Rep.        Asia      1962 35.180   6120081  825.6232
388 Yemen, Rep.        Asia      1967 36.984   6740785  862.4421
389 Yemen, Rep.        Asia      1972 39.848   7407075 1265.0470
390 Yemen, Rep.        Asia      1977 44.175   8403990 1829.7652
391 Yemen, Rep.        Asia      1982 49.113   9657618 1977.5570
392 Yemen, Rep.        Asia      1987 52.922  11219340 1971.7415
393 Yemen, Rep.        Asia      1992 55.599  13367997 1879.4967
394 Yemen, Rep.        Asia      1997 58.020  15826497 2117.4845
395 Yemen, Rep.        Asia      2002 60.308  18701257 2234.8208
396 Yemen, Rep.        Asia      2007 62.698  22211743 2280.7699

In [25]:
#Usamos el operador pipe
gapminder %>% filter(continent == 'Asia')

    country            continent year lifeExp pop      gdpPercap
1   Afghanistan        Asia      1952 28.801   8425333   779.4453
2   Afghanistan        Asia      1957 30.332   9240934   820.8530
3   Afghanistan        Asia      1962 31.997  10267083   853.1007
4   Afghanistan        Asia      1967 34.020  11537966   836.1971
5   Afghanistan        Asia      1972 36.088  13079460   739.9811
6   Afghanistan        Asia      1977 38.438  14880372   786.1134
7   Afghanistan        Asia      1982 39.854  12881816   978.0114
8   Afghanistan        Asia      1987 40.822  13867957   852.3959
9   Afghanistan        Asia      1992 41.674  16317921   649.3414
10  Afghanistan        Asia      1997 41.763  22227415   635.3414
11  Afghanistan        Asia      2002 42.129  25268405   726.7341
12  Afghanistan        Asia      2007 43.828  31889923   974.5803
13  Bahrain            Asia      1952 50.939    120447  9867.0848
14  Bahrain            Asia      1957 53.832    138655 11635.7995
15  Bahrain            Asia      1962 56.923    171863 12753.2751
16  Bahrain            Asia      1967 59.923    202182 14804.6727
17  Bahrain            Asia      1972 63.300    230800 18268.6584
18  Bahrain            Asia      1977 65.593    297410 19340.1020
19  Bahrain            Asia      1982 69.052    377967 19211.1473
20  Bahrain            Asia      1987 70.750    454612 18524.0241
21  Bahrain            Asia      1992 72.601    529491 19035.5792
22  Bahrain            Asia      1997 73.925    598561 20292.0168
23  Bahrain            Asia      2002 74.795    656397 23403.5593
24  Bahrain            Asia      2007 75.635    708573 29796.0483
25  Bangladesh         Asia      1952 37.484  46886859   684.2442
26  Bangladesh         Asia      1957 39.348  51365468   661.6375
27  Bangladesh         Asia      1962 41.216  56839289   686.3416
28  Bangladesh         Asia      1967 43.453  62821884   721.1861
29  Bangladesh         Asia      1972 45.252  70759295   630.2336
30  Bangladesh         Asia      1977 46.923  80428306   659.8772
... ...                ...       ...  ...     ...      ...
367 Vietnam            Asia      1982 58.816  56142181  707.2358
368 Vietnam            Asia      1987 62.820  62826491  820.7994
369 Vietnam            Asia      1992 67.662  69940728  989.0231
370 Vietnam            Asia      1997 70.672  76048996 1385.8968
371 Vietnam            Asia      2002 73.017  80908147 1764.4567
372 Vietnam            Asia      2007 74.249  85262356 2441.5764
373 West Bank and Gaza Asia      1952 43.160   1030585 1515.5923
374 West Bank and Gaza Asia      1957 45.671   1070439 1827.0677
375 West Bank and Gaza Asia      1962 48.127   1133134 2198.9563
376 West Bank and Gaza Asia      1967 51.631   1142636 2649.7150
377 West Bank and Gaza Asia      1972 56.532   1089572 3133.4093
378 West Bank and Gaza Asia      1977 60.765   1261091 3682.8315
379 West Bank and Gaza Asia      1982 64.406   1425876 4336.0321
380 West Bank and Gaza Asia      1987 67.046   1691210 5107.1974
381 West Bank and Gaza Asia      1992 69.718   2104779 6017.6548
382 West Bank and Gaza Asia      1997 71.096   2826046 7110.6676
383 West Bank and Gaza Asia      2002 72.370   3389578 4515.4876
384 West Bank and Gaza Asia      2007 73.422   4018332 3025.3498
385 Yemen, Rep.        Asia      1952 32.548   4963829  781.7176
386 Yemen, Rep.        Asia      1957 33.970   5498090  804.8305
387 Yemen, Rep.        Asia      1962 35.180   6120081  825.6232
388 Yemen, Rep.        Asia      1967 36.984   6740785  862.4421
389 Yemen, Rep.        Asia      1972 39.848   7407075 1265.0470
390 Yemen, Rep.        Asia      1977 44.175   8403990 1829.7652
391 Yemen, Rep.        Asia      1982 49.113   9657618 1977.5570
392 Yemen, Rep.        Asia      1987 52.922  11219340 1971.7415
393 Yemen, Rep.        Asia      1992 55.599  13367997 1879.4967
394 Yemen, Rep.        Asia      1997 58.020  15826497 2117.4845
395 Yemen, Rep.        Asia      2002 60.308  18701257 2234.8208
396 Yemen, Rep.        Asia      2007 62.698  22211743 2280.7699

In [28]:
#Mas de una condicion
gapminder%>%filter(lifeExp<=40,year == 2002)

  country  continent year lifeExp pop      gdpPercap
1 Zambia   Africa    2002 39.193  10595811 1071.6139
2 Zimbabwe Africa    2002 39.989  11926563  672.0386

In [30]:
gapminder %>% filter(continent == 'Asia', year == 2007)%>%summarise(conteo = n())
#Cuenta cuantos

  conteo
1 33

In [31]:
#El maximo por ejemplo
gapminder %>% filter(continent == 'Asia', year == 2007)%>%
summarise(MaxEsp = max(lifeExp))
#O sea primero filtra los paises que satisfacen eso y despues pidele algo, una media
#de alguna columna o que se yo

  MaxEsp
1 82.603

In [33]:
#groupby
gapminder%>%group_by(year)%>%summarise(MaxEsp=max(lifeExp))
#Es decir, para cada año, toma el maximo de la esperanza de vida

   year MaxEsp
1  1952 72.670
2  1957 73.470
3  1962 73.680
4  1967 74.160
5  1972 74.720
6  1977 76.110
7  1982 77.110
8  1987 78.670
9  1992 79.360
10 1997 80.690
11 2002 82.000
12 2007 82.603